/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/appointments` | `/appointments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/medicines` | `/medicines`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/myqr` | `/myqr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/network` | `/network`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/prescriptions` | `/prescriptions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/appointments` | `/appointments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/medicines` | `/medicines`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/myqr` | `/myqr`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/network` | `/network`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/prescriptions` | `/prescriptions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/appointments${`?${string}` | `#${string}` | ''}` | `/appointments${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/medicines${`?${string}` | `#${string}` | ''}` | `/medicines${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/myqr${`?${string}` | `#${string}` | ''}` | `/myqr${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/network${`?${string}` | `#${string}` | ''}` | `/network${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/prescriptions${`?${string}` | `#${string}` | ''}` | `/prescriptions${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/appointments` | `/appointments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/medicines` | `/medicines`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/myqr` | `/myqr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/network` | `/network`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/prescriptions` | `/prescriptions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
    }
  }
}
