const express = require('express');
const path = require('path');
const prisma = require('../lib/prisma');
const asyncHandler = require('../lib/async-handler');
const { createPrescriptionPdf } = require('../lib/pdf-documents');
const { resolveUploadPath } = require('../lib/storage-paths');

const router = express.Router();

router.get('/', asyncHandler(async (_req, res) => {
  const prescriptions = await prisma.prescription.findMany({
    include: {
      doctor: true,
      patient: true,
      items: true
    },
    orderBy: { startDate: 'desc' }
  });

  res.json(prescriptions);
}));

router.get('/:prescriptionId', asyncHandler(async (req, res) => {
  const prescription = await prisma.prescription.findUnique({
    where: { id: req.params.prescriptionId },
    include: {
      doctor: true,
      patient: true,
      items: true
    }
  });

  if (!prescription) {
    res.status(404).json({ error: 'Prescription not found' });
    return;
  }

  res.json(prescription);
}));

router.get('/:prescriptionId/pdf', asyncHandler(async (req, res) => {
  let prescription = await prisma.prescription.findUnique({
    where: { id: req.params.prescriptionId },
    include: {
      doctor: true,
      patient: true,
      items: true,
      labReports: true
    }
  });

  if (!prescription) {
    res.status(404).json({ error: 'Prescription not found' });
    return;
  }

  // Serve cached PDF if it already exists on disk (generated by EMR save)
  if (prescription.documentPath) {
    const cached = resolveUploadPath(prescription.documentPath);
    if (require('fs').existsSync(cached)) {
      if (req.query.download === '1') { res.download(cached); return; }
      res.sendFile(cached);
      return;
    }
  }

  // Generate PDF (only runs when no cached file exists)
  try {
    const { publicPath } = await createPrescriptionPdf(prescription);
    prescription = await prisma.prescription.update({
      where: { id: prescription.id },
      data: { documentPath: publicPath },
      include: { doctor: true, patient: true, items: true, labReports: true }
    });
    const absolutePath = resolveUploadPath(prescription.documentPath);
    if (req.query.download === '1') { res.download(absolutePath); return; }
    res.sendFile(absolutePath);
  } catch (pdfErr) {
    console.error('[PDF] Generation failed for prescription', prescription.id, ':', pdfErr.message);
    res.status(500).json({ error: 'PDF generation failed. Please try again.' });
  }
}));

module.exports = router;
